export const productsAndservices = [
  {
    id: 0,
    productName: "Internship training",
    productPrice: 30000,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 5,
      month: 1,
      year: 2008,
    },
  },
  {
    id: 1,
    productName: "Printing services",
    productPrice: 25,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 25,
      month: 1,
      year: 2007,
    },
  },
  {
    id: 2,
    productName: "Photocopying services",
    productPrice: 10,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 3,
      month: 2,
      year: 2005,
    },
  },
  {
    id: 3,
    productName: "Graphic design",
    productPrice: 62000,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 7,
      month: 2,
      year: 2005,
    },
  },
  {
    id: 4,
    productName: "Data analysis",
    productPrice: 75000,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 19,
      month: 6,
      year: 2022,
    },
  },
  {
    id: 5,
    productName: "Consultation",
    productPrice: 25000,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 12,
      month: 4,
      year: 2003,
    },
  },
  {
    id: 6,
    productName: "DELL Latitude E5450",
    productPrice: 125000,
    productType: "product",
    originalPrice: 74500,
    dateAdded: {
      day: 11,
      month: 4,
      year: 2024,
    },
  },
  {
    id: 7,
    productName: "HP Slim Desktop S01-pF4055t PC",
    productPrice: 131500,
    productType: "product",
    originalPrice: 93200,
    dateAdded: {
      day: 11,
      month: 4,
      year: 2024,
    },
  },
  {
    id: 8,
    productName: "OMEN by HP 25L Gaming Desktop GT15-2085t PC",
    productPrice: 500000,
    productType: "product",
    originalPrice: 350000,
    dateAdded: {
      day: 1,
      month: 2,
      year: 2024,
    },
  },
  {
    id: 9,
    productName: "OMEN 45L Gaming Desktop GT22-2000t",
    productPrice: 623000,
    productType: "product",
    originalPrice: 477000,
    dateAdded: {
      day: 2,
      month: 4,
      year: 2024,
    },
  },
  {
    id: 10,
    productName: "Networking services",
    productPrice: 25000,
    productType: "service",
    originalPrice: 0,
    dateAdded: {
      day: 24,
      month: 6,
      year: 2004,
    },
  },
  {
    id: 11,
    productName: "Ethernet cables",
    productPrice: 3200,
    productType: "product",
    originalPrice: 700,
    dateAdded: {
      day: 28,
      month: 6,
      year: 2004,
    },
  },
];
